### ISSUE TITLE
Migration requires S3 configuration

### ISSUE THREAD

**Issue by jasonaowen** [PhilanthropyDataCommons/service#1229]
Running the database migrations fails if the S3-related environment variables are not provided. This is both surprising and violates the principle of least privilege.

```
$ npm run migrate

> migrate
> ts-node src/scripts/migrate.ts | pino-pretty

src/s3Client.ts:10
} = requireEnv(
              ^
Error: Environment variables missing: [ "S3_ACCESS_KEY_ID", "S3_ACCESS_SECRET", "S3_ENDPOINT", "S3_PATH_STYLE", "S3_REGION" ]
    at Object.<anonymous> (src/s3Client.ts:10:15)
    at Module._compile (node:internal/modules/cjs/loader:1358:14)
    at Module.m._compile (node_modules/ts-node/src/index.ts:1618:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
    at Object.require.extensions.<computed> [as .ts] (node_modules/ts-node/src/index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:1208:32)
    at Function.Module._load (node:internal/modules/cjs/loader:1024:12)
    at Module.require (node:internal/modules/cjs/loader:1233:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (src/tasks/processBulkUpload.ts:6:1)
```

**Comment by slifty** [comment]
this is true but it is basically the state of the project.  If it comes up as an issue in future as a problem we can address it!
