### ISSUE TITLE
openapi.json Issue

### ISSUE THREAD

**Issue by mortimal1** [PhilanthropyDataCommons/service#316]
I'm seeing errors in the openapi.json file and client generation fails with the following error:
Errors: 
	-attribute parameters is unexpected
	-attribute components.schemas.Bundle.items is missing
	-attribute paths.'/proposals'(get).parameters.There are duplicate parameter values

	at org.openapitools.codegen.config.CodegenConfigurator.toContext(CodegenConfigurator.java:541)
	at org.openapitools.codegen.config.CodegenConfigurator.toClientOptInput(CodegenConfigurator.java:568)
	at org.openapitools.codegen.cmd.Generate.execute(Generate.java:424)
	at org.openapitools.codegen.cmd.OpenApiGeneratorCommand.run(OpenApiGeneratorCommand.java:32)
	at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:66)

**Comment by slifty** [comment]
Thank you for the heads up!

One note: `-attribute components.schemas.Bundle.items is missing` should be resolved now thanks to https://github.com/PhilanthropyDataCommons/service/commit/d78952852d53f4f058d305c73a462b2f2cd4d0ec

I'll look into the other two now.

**Comment by slifty** [comment]
@mortimal1 when you have a moment, would you be able to see if this results in any errors: https://github.com/PhilanthropyDataCommons/service/blob/316-fix-openapi/src/openapi.json

**Comment by mortimal1** [comment]
That ran successfully, thank you
