### ISSUE TITLE
Error logs do not contain useful information

### ISSUE THREAD

**Issue by jasonaowen** [PhilanthropyDataCommons/service#350]
When something is wrong with the service, error logs are the first place we look. Unfortunately, I've been finding that while they log the fact of the error - which is useful - they do not tend to include the cause of the error.

<details>
<summary>Example log message</summary>

```
[2023-05-11T19:54:52.375Z] INFO (1292163): request errored
    source: "src/app.ts"
    req: {
      "id": 7,
      "method": "GET",
      "url": "/baseFields",
      "query": {},
      "params": {},
      "headers": {
        "host": "localhost:3000",
        "user-agent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/112.0",
        "accept": "application/json",
        "accept-language": "en-US,en;q=0.5",
        "accept-encoding": "gzip, deflate, br",
        "referer": "http://localhost:3001/",
        "authorization": "Bearer [omitted for brevity]",
        "origin": "http://localhost:3001",
        "dnt": "1",
        "connection": "keep-alive",
        "sec-fetch-dest": "empty",
        "sec-fetch-mode": "cors",
        "sec-fetch-site": "same-site"
      },
      "remoteAddress": "127.0.0.1",
      "remotePort": 33990
    }
    res: {
      "statusCode": 500,
      "headers": {
        "x-powered-by": "Express",
        "access-control-allow-origin": "*",
        "content-type": "application/json; charset=utf-8",
        "content-length": "224",
        "etag": "W/\"e0-kJB3uym6Y/jOI2j5KTf3FlXOZlk\""
      }
    }
    responseTime: 32
    err: {
      "type": "Error",
      "message": "failed with status code 500",
      "stack":
          Error: failed with status code 500
              at onResFinished (node_modules/pino-http/logger.js:110:39)
              at ServerResponse.onResponseComplete (node_modules/pino-http/logger.js:173:14)
              at ServerResponse.emit (node:events:525:35)
              at ServerResponse.emit (node:domain:489:12)
              at onFinish (node:_http_outgoing:967:10)
              at callback (node:internal/streams/writable:555:21)
              at afterWrite (node:internal/streams/writable:500:5)
              at afterWriteTick (node:internal/streams/writable:487:10)
              at processTicksAndRejections (node:internal/process/task_queues:81:21)
    }
```
</details>

We should be logging the underlying error that led to a 500 response. In this example, the cause is a failed database query as I'd switched to a branch that renamed tables but hadn't run the migrations, but that is not at all evident in the logs.

**Comment by bickelj** [comment]
What you see above is the request log which will happen for every successful and failed request at info level.

In a development environment, the easiest way to see these is to enable debug logging, e.g. `LOG_LEVEL=debug`. The first line of the `errorHandler` function in `errorHandler.ts` emits the error in a separate debug message from the http request logs:
```typescript
export const errorHandler = (
  err: unknown,
  req: Request,
  res: Response,
  next: NextFunction, // eslint-disable-line @typescript-eslint/no-unused-vars
): void => {
  logger.debug(err);
```

Something we wouldn't want to do is include the exact details in the response body to the caller (and hence the request logs), so I think the solution is something like "change `.debug(err)` to `.error(err)`.
